apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

## PrefixSuffixTransformer
namePrefix: ""

## NamespaceTransformer
namespace: hipster-shop

## LabelTransformer
commonLabels:

## ImageTagTransformer
images:
- name: gcr.io/google-samples/microservices-demo/recommendationservice
  newTag: v0.1.3

bases:
- ../../base
