apiVersion: v1
kind: Service
metadata:
  name: core-dns-udp
  namespace: kube-system
  annotations:
      metallb.universe.tf/allow-shared-ip: kube-dns
spec:
  selector:
    k8s-app: kube-dns
  type: LoadBalancer
  ports:
  - port: 53
    protocol: UDP
    targetPort: 53
  loadBalancerIP: 172.17.255.2
---
apiVersion: v1
kind: Service
metadata:
  name: core-dns-tcp
  namespace: kube-system
  annotations:
      metallb.universe.tf/allow-shared-ip: kube-dns
spec:
  selector:
    k8s-app: kube-dns
  type: LoadBalancer
  ports:
  - port: 53
    protocol: TCP
    targetPort: 53
  loadBalancerIP: 172.17.255.2

