apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: carol-pod-viewer
subjects:
- kind: ServiceAccount
  name: carol
  namespace: prometheus
roleRef:
  kind: ClusterRole
  name: view-all-pods
  apiGroup: rbac.authorization.k8s.io
