apiVersion: v1
kind: Service
metadata:
  name: nginx
spec:
  selector:
    app: nginx
  ports:
    - name: web
      protocol: TCP
      port: 8000
      targetPort: 8000
    - name: metrics
      protocol: TCP
      port: 9113
      targetPort: 9113
